Link/Controllers/PeopleController.cs
#region Auto generated information. Please do not modify

// Link Link PeopleController.cs
// OTTPC 
// 2016-09-02 22:23
// 2016-09-02 21:58

#endregion

using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using Link.DAL;
using Link.Models;

namespace Link.Controllers
{
    public class PeopleController : Controller
    {
        public PeopleController(IPeopleRepository peopleRepository)
        {
            this.peopleRepository = peopleRepository;
        }

        private IPeopleRepository peopleRepository;
        private readonly LinkDbContext db = new LinkDbContext();
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "PersonId,FirstName,LastName,DateOfBirth,DateCreated,DateModified")] Person person)
        {
            if(ModelState.IsValid)
            {
                var createdPerson = peopleRepository.CreatePerson(person);
                if(createdPerson != null)
                {
                    return RedirectToAction("Create", "Websites", new {id = person.PersonId});
                }
                Response.Write(
                    "<script>alert('This person already exists in the database.')</script>");

            }

            return View(person);
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Link/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
            
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Insert websites", "Create", "People")</li>
                    <li>@Html.ActionLink("Top websites", "Index", "Websites")</li>
                </ul>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lauri Miller</p>
        </footer>
    </div>

     @Scripts.Render("~/bundles/jquery")
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
    </script>
</body>
</html>